CREATE TABLE IF NOT EXISTS conversations (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	sender_id INTEGER NOT NULL,
	receiver_id INTEGER NOT NULL,
	last_message_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	seen INTEGER DEFAULT 0 CHECK (seen IN (0, 1)),
	FOREIGN KEY (sender_id) REFERENCES users (user_id) ON DELETE CASCADE,
	FOREIGN KEY (receiver_id) REFERENCES users (user_id) ON DELETE CASCADE
);